#include "wilfred/search/glyphs.hpp"

#include "wilfred/core/utf8.hpp"
#include "wilfred/search/fuzzy.hpp"

#include <algorithm>
#include <string>
#include <vector>

namespace wilfred {
namespace {

struct Glyph {
  const char* ch;
  const char* name;
  const char* tags;
  bool symbol;
};

const Glyph kGlyphs[] = {
    {"😀", "grinning face", "smile happy grin", false},
    {"😃", "grinning face with big eyes", "smile happy", false},
    {"😄", "grinning face with smiling eyes", "smile happy laugh", false},
    {"😁", "beaming face", "smile grin teeth", false},
    {"😆", "grinning squinting face", "laugh haha", false},
    {"😅", "grinning face with sweat", "relief nervous", false},
    {"🤣", "rolling on the floor laughing", "rofl lol", false},
    {"😂", "face with tears of joy", "lol cry laugh", false},
    {"🙂", "slightly smiling face", "smile", false},
    {"😉", "winking face", "wink flirt", false},
    {"😊", "smiling face with smiling eyes", "blush happy", false},
    {"😇", "smiling face with halo", "angel innocent", false},
    {"🥰", "smiling face with hearts", "love crush", false},
    {"😍", "smiling face with heart-eyes", "love crush", false},
    {"🤩", "star-struck", "stars wow", false},
    {"😘", "face blowing a kiss", "kiss love", false},
    {"😗", "kissing face", "kiss", false},
    {"😚", "kissing face with closed eyes", "kiss", false},
    {"😋", "face savoring food", "yum tasty", false},
    {"😛", "face with tongue", "tongue playful", false},
    {"😜", "winking face with tongue", "wink tongue", false},
    {"🤪", "zany face", "goofy crazy", false},
    {"😝", "squinting face with tongue", "tongue", false},
    {"🤑", "money-mouth face", "money rich dollar", false},
    {"🤗", "hugging face", "hug", false},
    {"🤭", "face with hand over mouth", "oops secret", false},
    {"🤫", "shushing face", "quiet secret", false},
    {"🤔", "thinking face", "think hmm", false},
    {"🤐", "zipper-mouth face", "secret quiet", false},
    {"🤨", "face with raised eyebrow", "skeptical", false},
    {"😐", "neutral face", "meh", false},
    {"😑", "expressionless face", "blank", false},
    {"😶", "face without mouth", "silent", false},
    {"😏", "smirking face", "smirk", false},
    {"😒", "unamused face", "meh annoyed", false},
    {"🙄", "face with rolling eyes", "eyeroll", false},
    {"😬", "grimacing face", "awkward", false},
    {"🤥", "lying face", "pinocchio lie", false},
    {"😌", "relieved face", "calm", false},
    {"😔", "pensive face", "sad", false},
    {"😪", "sleepy face", "tired", false},
    {"🤤", "drooling face", "hungry", false},
    {"😴", "sleeping face", "sleep zzz", false},
    {"😷", "face with medical mask", "sick mask", false},
    {"🤒", "face with thermometer", "sick fever", false},
    {"🤕", "face with head-bandage", "hurt injury", false},
    {"🤢", "nauseated face", "sick vomit", false},
    {"🤮", "face vomiting", "sick vomit", false},
    {"🤧", "sneezing face", "sick sneeze", false},
    {"🥵", "hot face", "heat sweaty", false},
    {"🥶", "cold face", "freeze", false},
    {"🥴", "woozy face", "drunk dizzy", false},
    {"😵", "dizzy face", "dead knockout", false},
    {"🤯", "exploding head", "mind blown", false},
    {"🤠", "cowboy hat face", "cowboy", false},
    {"🥳", "partying face", "party celebrate", false},
    {"😎", "smiling face with sunglasses", "cool", false},
    {"🤓", "nerd face", "geek glasses", false},
    {"🧐", "face with monocle", "inspect", false},
    {"😕", "confused face", "confused", false},
    {"😟", "worried face", "worry", false},
    {"🙁", "slightly frowning face", "sad frown", false},
    {"☹️", "frowning face", "sad", false},
    {"😮", "face with open mouth", "wow surprise", false},
    {"😯", "hushed face", "surprise", false},
    {"😲", "astonished face", "shock", false},
    {"😳", "flushed face", "embarrassed", false},
    {"🥺", "pleading face", "please puppy", false},
    {"😦", "frowning face with open mouth", "shock", false},
    {"😧", "anguished face", "pain", false},
    {"😨", "fearful face", "scared", false},
    {"😰", "anxious face with sweat", "nervous", false},
    {"😥", "sad but relieved face", "disappointed", false},
    {"😢", "crying face", "sad tear", false},
    {"😭", "loudly crying face", "sob cry", false},
    {"😱", "face screaming in fear", "scream scared", false},
    {"😖", "confounded face", "frustrated", false},
    {"😣", "persevering face", "struggle", false},
    {"😞", "disappointed face", "sad", false},
    {"😓", "downcast face with sweat", "tired", false},
    {"😩", "weary face", "tired", false},
    {"😫", "tired face", "exhausted", false},
    {"🥱", "yawning face", "bored tired", false},
    {"😤", "face with steam from nose", "angry huff", false},
    {"😡", "pouting face", "angry mad", false},
    {"😠", "angry face", "mad", false},
    {"🤬", "face with symbols on mouth", "swear cursing", false},
    {"😈", "smiling face with horns", "devil", false},
    {"👿", "angry face with horns", "devil", false},
    {"💀", "skull", "dead death", false},
    {"☠️", "skull and crossbones", "poison pirate", false},
    {"💩", "pile of poo", "poop", false},
    {"🤡", "clown face", "clown", false},
    {"👻", "ghost", "halloween", false},
    {"👽", "alien", "ufo", false},
    {"👾", "alien monster", "game space", false},
    {"🤖", "robot", "bot", false},
    {"😺", "grinning cat", "cat smile", false},
    {"😸", "grinning cat with smiling eyes", "cat", false},
    {"😹", "cat with tears of joy", "cat lol", false},
    {"😻", "smiling cat with heart-eyes", "cat love", false},
    {"😼", "cat with wry smile", "cat smirk", false},
    {"😽", "kissing cat", "cat kiss", false},
    {"🙀", "weary cat", "cat shock", false},
    {"😿", "crying cat", "cat sad", false},
    {"😾", "pouting cat", "cat angry", false},
    {"🙈", "see-no-evil monkey", "monkey hide", false},
    {"🙉", "hear-no-evil monkey", "monkey", false},
    {"🙊", "speak-no-evil monkey", "monkey quiet", false},
    {"💋", "kiss mark", "lips", false},
    {"💌", "love letter", "mail heart", false},
    {"💘", "heart with arrow", "cupid love", false},
    {"💝", "heart with ribbon", "gift love", false},
    {"💖", "sparkling heart", "love sparkle", false},
    {"💗", "growing heart", "love", false},
    {"💓", "beating heart", "love pulse", false},
    {"💞", "revolving hearts", "love", false},
    {"💕", "two hearts", "love", false},
    {"💟", "heart decoration", "love", false},
    {"❣️", "heart exclamation", "love", false},
    {"💔", "broken heart", "heartbreak sad", false},
    {"❤️", "red heart", "love heart", false},
    {"🧡", "orange heart", "love", false},
    {"💛", "yellow heart", "love", false},
    {"💚", "green heart", "love", false},
    {"💙", "blue heart", "love", false},
    {"💜", "purple heart", "love", false},
    {"🖤", "black heart", "love", false},
    {"🤍", "white heart", "love", false},
    {"🤎", "brown heart", "love", false},
    {"💯", "hundred points", "100 perfect score", false},
    {"💢", "anger symbol", "mad", false},
    {"💥", "collision", "boom explode", false},
    {"💫", "dizzy", "stars", false},
    {"💦", "sweat droplets", "water", false},
    {"💨", "dashing away", "fast wind", false},
    {"👋", "waving hand", "hello bye wave", false},
    {"🤚", "raised back of hand", "hand", false},
    {"🖐️", "hand with fingers splayed", "hand five", false},
    {"✋", "raised hand", "stop high five", false},
    {"🖖", "vulcan salute", "spock", false},
    {"👌", "ok hand", "okay perfect", false},
    {"✌️", "victory hand", "peace", false},
    {"🤞", "crossed fingers", "luck", false},
    {"🤟", "love-you gesture", "ily", false},
    {"🤘", "sign of the horns", "rock metal", false},
    {"🤙", "call me hand", "shaka phone", false},
    {"👈", "backhand index pointing left", "left", false},
    {"👉", "backhand index pointing right", "right", false},
    {"👆", "backhand index pointing up", "up", false},
    {"👇", "backhand index pointing down", "down", false},
    {"☝️", "index pointing up", "up", false},
    {"👍", "thumbs up", "like yes ok", false},
    {"👎", "thumbs down", "dislike no", false},
    {"✊", "raised fist", "power", false},
    {"👊", "oncoming fist", "punch", false},
    {"🤛", "left-facing fist", "punch", false},
    {"🤜", "right-facing fist", "punch", false},
    {"👏", "clapping hands", "clap applause", false},
    {"🙌", "raising hands", "hooray praise", false},
    {"👐", "open hands", "hands", false},
    {"🤲", "palms up together", "pray offer", false},
    {"🤝", "handshake", "deal agree", false},
    {"🙏", "folded hands", "please thanks pray", false},
    {"✍️", "writing hand", "write", false},
    {"💅", "nail polish", "nails", false},
    {"🤳", "selfie", "phone", false},
    {"💪", "flexed biceps", "strong muscle", false},
    {"🦾", "mechanical arm", "robot", false},
    {"🦵", "leg", "kick", false},
    {"🦶", "foot", "kick", false},
    {"👂", "ear", "hear", false},
    {"👃", "nose", "smell", false},
    {"🧠", "brain", "smart think", false},
    {"👀", "eyes", "look see", false},
    {"👁️", "eye", "see", false},
    {"👅", "tongue", "taste", false},
    {"👄", "mouth", "lips", false},
    {"👶", "baby", "child", false},
    {"🧒", "child", "kid", false},
    {"👦", "boy", "kid", false},
    {"👧", "girl", "kid", false},
    {"🧑", "person", "adult", false},
    {"👱", "person blond hair", "blond", false},
    {"👨", "man", "male", false},
    {"👩", "woman", "female", false},
    {"🧓", "older person", "elder", false},
    {"👴", "old man", "elder", false},
    {"👵", "old woman", "elder", false},
    {"🙍", "person frowning", "sad", false},
    {"🙎", "person pouting", "annoyed", false},
    {"🙅", "person gesturing no", "no stop", false},
    {"🙆", "person gesturing ok", "ok", false},
    {"💁", "person tipping hand", "info sassy", false},
    {"🙋", "person raising hand", "question", false},
    {"🙇", "person bowing", "sorry bow", false},
    {"🤦", "person facepalming", "facepalm", false},
    {"🤷", "person shrugging", "shrug idk", false},
    {"👮", "police officer", "cop police", false},
    {"🕵️", "detective", "spy", false},
    {"💂", "guard", "britain", false},
    {"🥷", "ninja", "stealth", false},
    {"👷", "construction worker", "builder", false},
    {"🤴", "prince", "royal", false},
    {"👸", "princess", "royal", false},
    {"👳", "person wearing turban", "turban", false},
    {"👲", "person with skullcap", "hat", false},
    {"🧕", "woman with headscarf", "hijab", false},
    {"🤵", "person in tuxedo", "wedding", false},
    {"👰", "person with veil", "wedding bride", false},
    {"🤰", "pregnant woman", "baby", false},
    {"🤱", "breast-feeding", "baby", false},
    {"👼", "baby angel", "cherub", false},
    {"🎅", "santa claus", "christmas", false},
    {"🤶", "mrs claus", "christmas", false},
    {"🦸", "superhero", "hero", false},
    {"🦹", "supervillain", "villain", false},
    {"🧙", "mage", "wizard magic", false},
    {"🧚", "fairy", "magic", false},
    {"🧛", "vampire", "dracula", false},
    {"🧜", "merperson", "mermaid", false},
    {"🧝", "elf", "fantasy", false},
    {"🧞", "genie", "lamp", false},
    {"🧟", "zombie", "undead", false},
    {"💆", "person getting massage", "spa", false},
    {"💇", "person getting haircut", "salon", false},
    {"🚶", "person walking", "walk", false},
    {"🧍", "person standing", "stand", false},
    {"🧎", "person kneeling", "kneel", false},
    {"🏃", "person running", "run", false},
    {"💃", "woman dancing", "dance", false},
    {"🕺", "man dancing", "dance", false},
    {"🕴️", "person in suit levitating", "hover", false},
    {"👯", "people with bunny ears", "dance party", false},
    {"🧖", "person in steamy room", "sauna", false},
    {"🧗", "person climbing", "climb", false},
    {"🤺", "person fencing", "sword", false},
    {"🏇", "horse racing", "jockey", false},
    {"⛷️", "skier", "ski snow", false},
    {"🏂", "snowboarder", "snow", false},
    {"🏌️", "person golfing", "golf", false},
    {"🏄", "person surfing", "surf", false},
    {"🚣", "person rowing boat", "boat", false},
    {"🏊", "person swimming", "swim", false},
    {"⛹️", "person bouncing ball", "basketball", false},
    {"🏋️", "person lifting weights", "gym", false},
    {"🚴", "person biking", "bike", false},
    {"🚵", "person mountain biking", "bike", false},
    {"🤸", "person cartwheeling", "gymnast", false},
    {"🤼", "people wrestling", "wrestle", false},
    {"🤽", "person playing water polo", "polo", false},
    {"🤾", "person playing handball", "handball", false},
    {"🤹", "person juggling", "juggle", false},
    {"🧘", "person in lotus position", "yoga meditate", false},
    {"🛀", "person taking bath", "bath", false},
    {"🛌", "person in bed", "sleep", false},
    {"👭", "women holding hands", "friends", false},
    {"👫", "woman and man holding hands", "couple", false},
    {"👬", "men holding hands", "friends", false},
    {"💏", "kiss", "couple love", false},
    {"💑", "couple with heart", "love", false},
    {"👪", "family", "parents", false},
    {"🗣️", "speaking head", "talk", false},
    {"👤", "bust in silhouette", "user person", false},
    {"👥", "busts in silhouette", "users people", false},
    {"🫂", "people hugging", "hug", false},
    {"🐶", "dog face", "dog puppy pet", false},
    {"🐱", "cat face", "cat kitten pet", false},
    {"🐭", "mouse face", "mouse", false},
    {"🐹", "hamster", "pet", false},
    {"🐰", "rabbit face", "bunny", false},
    {"🦊", "fox", "animal", false},
    {"🐻", "bear", "animal", false},
    {"🐼", "panda", "bear", false},
    {"🐨", "koala", "animal", false},
    {"🐯", "tiger face", "animal", false},
    {"🦁", "lion", "animal", false},
    {"🐮", "cow face", "animal", false},
    {"🐷", "pig face", "animal", false},
    {"🐸", "frog", "animal", false},
    {"🐵", "monkey face", "animal", false},
    {"🙈", "see-no-evil monkey", "monkey", false},
    {"🐔", "chicken", "bird", false},
    {"🐧", "penguin", "bird", false},
    {"🐦", "bird", "animal", false},
    {"🐤", "baby chick", "bird", false},
    {"🦆", "duck", "bird", false},
    {"🦅", "eagle", "bird", false},
    {"🦉", "owl", "bird", false},
    {"🦇", "bat", "animal", false},
    {"🐺", "wolf", "animal", false},
    {"🐗", "boar", "animal", false},
    {"🐴", "horse face", "animal", false},
    {"🦄", "unicorn", "magic", false},
    {"🐝", "honeybee", "insect", false},
    {"🐛", "bug", "insect", false},
    {"🦋", "butterfly", "insect", false},
    {"🐌", "snail", "slow", false},
    {"🐞", "lady beetle", "bug", false},
    {"🐜", "ant", "insect", false},
    {"🦟", "mosquito", "insect", false},
    {"🦗", "cricket", "insect", false},
    {"🕷️", "spider", "insect", false},
    {"🦂", "scorpion", "animal", false},
    {"🐢", "turtle", "animal", false},
    {"🐍", "snake", "animal", false},
    {"🦎", "lizard", "animal", false},
    {"🦖", "t-rex", "dinosaur", false},
    {"🦕", "sauropod", "dinosaur", false},
    {"🐙", "octopus", "sea", false},
    {"🦑", "squid", "sea", false},
    {"🦐", "shrimp", "sea", false},
    {"🦀", "crab", "sea", false},
    {"🐡", "blowfish", "fish", false},
    {"🐠", "tropical fish", "fish", false},
    {"🐟", "fish", "sea", false},
    {"🐬", "dolphin", "sea", false},
    {"🐳", "spouting whale", "sea", false},
    {"🐋", "whale", "sea", false},
    {"🦈", "shark", "sea", false},
    {"🐊", "crocodile", "animal", false},
    {"🐅", "tiger", "animal", false},
    {"🐆", "leopard", "animal", false},
    {"🦓", "zebra", "animal", false},
    {"🦍", "gorilla", "animal", false},
    {"🦧", "orangutan", "animal", false},
    {"🐘", "elephant", "animal", false},
    {"🦛", "hippopotamus", "animal", false},
    {"🦏", "rhinoceros", "animal", false},
    {"🐪", "camel", "animal", false},
    {"🐫", "two-hump camel", "animal", false},
    {"🦒", "giraffe", "animal", false},
    {"🦘", "kangaroo", "animal", false},
    {"🦬", "bison", "animal", false},
    {"🐃", "water buffalo", "animal", false},
    {"🐂", "ox", "animal", false},
    {"🐄", "cow", "animal", false},
    {"🐎", "horse", "animal", false},
    {"🐖", "pig", "animal", false},
    {"🐏", "ram", "animal", false},
    {"🐑", "ewe", "sheep", false},
    {"🦙", "llama", "animal", false},
    {"🐐", "goat", "animal", false},
    {"🦌", "deer", "animal", false},
    {"🐕", "dog", "pet", false},
    {"🐩", "poodle", "dog", false},
    {"🦮", "guide dog", "dog", false},
    {"🐈", "cat", "pet", false},
    {"🐓", "rooster", "bird", false},
    {"🦃", "turkey", "bird", false},
    {"🦚", "peacock", "bird", false},
    {"🦜", "parrot", "bird", false},
    {"🦢", "swan", "bird", false},
    {"🦩", "flamingo", "bird", false},
    {"🕊️", "dove", "peace bird", false},
    {"🐇", "rabbit", "bunny", false},
    {"🦝", "raccoon", "animal", false},
    {"🦨", "skunk", "animal", false},
    {"🦡", "badger", "animal", false},
    {"🦫", "beaver", "animal", false},
    {"🦦", "otter", "animal", false},
    {"🦥", "sloth", "slow", false},
    {"🐁", "mouse", "animal", false},
    {"🐀", "rat", "animal", false},
    {"🐿️", "chipmunk", "animal", false},
    {"🦔", "hedgehog", "animal", false},
    {"🐾", "paw prints", "pet tracks", false},
    {"🐉", "dragon", "myth", false},
    {"🐲", "dragon face", "myth", false},
    {"🌵", "cactus", "plant desert", false},
    {"🎄", "christmas tree", "holiday", false},
    {"🌲", "evergreen tree", "tree", false},
    {"🌳", "deciduous tree", "tree", false},
    {"🌴", "palm tree", "tropical", false},
    {"🌱", "seedling", "plant grow", false},
    {"🌿", "herb", "leaf", false},
    {"☘️", "shamrock", "clover luck", false},
    {"🍀", "four leaf clover", "luck", false},
    {"🎍", "pine decoration", "bamboo", false},
    {"🍃", "leaf fluttering in wind", "leaf", false},
    {"🍂", "fallen leaf", "autumn", false},
    {"🍁", "maple leaf", "canada autumn", false},
    {"🍄", "mushroom", "fungus", false},
    {"🌾", "sheaf of rice", "grain", false},
    {"💐", "bouquet", "flowers", false},
    {"🌷", "tulip", "flower", false},
    {"🌹", "rose", "flower love", false},
    {"🥀", "wilted flower", "sad", false},
    {"🌺", "hibiscus", "flower", false},
    {"🌸", "cherry blossom", "flower sakura", false},
    {"🌼", "blossom", "flower", false},
    {"🌻", "sunflower", "flower", false},
    {"🌞", "sun with face", "sun", false},
    {"🌝", "full moon face", "moon", false},
    {"🌛", "first quarter moon face", "moon", false},
    {"🌜", "last quarter moon face", "moon", false},
    {"🌚", "new moon face", "moon", false},
    {"🌕", "full moon", "moon", false},
    {"🌖", "waning gibbous moon", "moon", false},
    {"🌗", "last quarter moon", "moon", false},
    {"🌘", "waning crescent moon", "moon", false},
    {"🌑", "new moon", "moon", false},
    {"🌒", "waxing crescent moon", "moon", false},
    {"🌓", "first quarter moon", "moon", false},
    {"🌔", "waxing gibbous moon", "moon", false},
    {"🌙", "crescent moon", "night", false},
    {"🌎", "globe americas", "earth world", false},
    {"🌍", "globe europe-africa", "earth world", false},
    {"🌏", "globe asia-australia", "earth world", false},
    {"🪐", "ringed planet", "saturn space", false},
    {"💫", "dizzy", "star", false},
    {"⭐", "star", "favorite", false},
    {"🌟", "glowing star", "sparkle", false},
    {"✨", "sparkles", "magic glitter", false},
    {"⚡", "high voltage", "lightning zap", false},
    {"☄️", "comet", "space", false},
    {"💥", "collision", "boom", false},
    {"🔥", "fire", "lit hot flame", false},
    {"🌪️", "tornado", "storm", false},
    {"🌈", "rainbow", "pride weather", false},
    {"☀️", "sun", "sunny weather", false},
    {"🌤️", "sun behind small cloud", "weather", false},
    {"⛅", "sun behind cloud", "weather", false},
    {"🌥️", "sun behind large cloud", "weather", false},
    {"☁️", "cloud", "weather", false},
    {"🌦️", "sun behind rain cloud", "weather", false},
    {"🌧️", "cloud with rain", "weather rain", false},
    {"⛈️", "cloud with lightning and rain", "storm", false},
    {"🌩️", "cloud with lightning", "storm", false},
    {"🌨️", "cloud with snow", "snow", false},
    {"❄️", "snowflake", "cold winter", false},
    {"☃️", "snowman", "winter", false},
    {"⛄", "snowman without snow", "winter", false},
    {"🌬️", "wind face", "blow", false},
    {"💨", "dashing away", "wind", false},
    {"💧", "droplet", "water", false},
    {"💦", "sweat droplets", "water", false},
    {"☔", "umbrella with rain drops", "rain", false},
    {"☂️", "umbrella", "rain", false},
    {"🌊", "water wave", "ocean sea", false},
    {"🌫️", "fog", "weather", false},
    {"🍎", "red apple", "fruit", false},
    {"🍏", "green apple", "fruit", false},
    {"🍐", "pear", "fruit", false},
    {"🍊", "tangerine", "orange fruit", false},
    {"🍋", "lemon", "fruit", false},
    {"🍌", "banana", "fruit", false},
    {"🍉", "watermelon", "fruit", false},
    {"🍇", "grapes", "fruit", false},
    {"🍓", "strawberry", "fruit", false},
    {"🫐", "blueberries", "fruit", false},
    {"🍈", "melon", "fruit", false},
    {"🍒", "cherries", "fruit", false},
    {"🍑", "peach", "fruit", false},
    {"🥭", "mango", "fruit", false},
    {"🍍", "pineapple", "fruit", false},
    {"🥥", "coconut", "fruit", false},
    {"🥝", "kiwi fruit", "fruit", false},
    {"🍅", "tomato", "veggie", false},
    {"🍆", "eggplant", "veggie", false},
    {"🥑", "avocado", "fruit", false},
    {"🥦", "broccoli", "veggie", false},
    {"🥬", "leafy green", "veggie", false},
    {"🥒", "cucumber", "veggie", false},
    {"🌶️", "hot pepper", "spicy", false},
    {"🫑", "bell pepper", "veggie", false},
    {"🌽", "ear of corn", "veggie", false},
    {"🥕", "carrot", "veggie", false},
    {"🫒", "olive", "food", false},
    {"🧄", "garlic", "food", false},
    {"🧅", "onion", "food", false},
    {"🥔", "potato", "veggie", false},
    {"🍠", "roasted sweet potato", "food", false},
    {"🥐", "croissant", "bread", false},
    {"🥯", "bagel", "bread", false},
    {"🍞", "bread", "food", false},
    {"🥖", "baguette bread", "food", false},
    {"🥨", "pretzel", "food", false},
    {"🧀", "cheese wedge", "food", false},
    {"🥚", "egg", "food", false},
    {"🍳", "cooking", "egg breakfast", false},
    {"🧈", "butter", "food", false},
    {"🥞", "pancakes", "breakfast", false},
    {"🧇", "waffle", "breakfast", false},
    {"🥓", "bacon", "food", false},
    {"🥩", "cut of meat", "steak", false},
    {"🍗", "poultry leg", "chicken", false},
    {"🍖", "meat on bone", "food", false},
    {"🦴", "bone", "food", false},
    {"🌭", "hot dog", "food", false},
    {"🍔", "hamburger", "burger food", false},
    {"🍟", "french fries", "food", false},
    {"🍕", "pizza", "food", false},
    {"🫓", "flatbread", "food", false},
    {"🥪", "sandwich", "food", false},
    {"🥙", "stuffed flatbread", "food", false},
    {"🧆", "falafel", "food", false},
    {"🌮", "taco", "food", false},
    {"🌯", "burrito", "food", false},
    {"🫔", "tamale", "food", false},
    {"🥗", "green salad", "food", false},
    {"🥘", "shallow pan of food", "paella", false},
    {"🫕", "fondue", "food", false},
    {"🥫", "canned food", "food", false},
    {"🍝", "spaghetti", "pasta", false},
    {"🍜", "steaming bowl", "ramen noodles", false},
    {"🍲", "pot of food", "stew", false},
    {"🍛", "curry rice", "food", false},
    {"🍣", "sushi", "food", false},
    {"🍱", "bento box", "food", false},
    {"🥟", "dumpling", "food", false},
    {"🦪", "oyster", "seafood", false},
    {"🍤", "fried shrimp", "food", false},
    {"🍙", "rice ball", "food", false},
    {"🍚", "cooked rice", "food", false},
    {"🍘", "rice cracker", "food", false},
    {"🍥", "fish cake with swirl", "food", false},
    {"🥠", "fortune cookie", "food", false},
    {"🥮", "moon cake", "food", false},
    {"🍢", "oden", "food", false},
    {"🍡", "dango", "food", false},
    {"🍧", "shaved ice", "dessert", false},
    {"🍨", "ice cream", "dessert", false},
    {"🍦", "soft ice cream", "dessert", false},
    {"🥧", "pie", "dessert", false},
    {"🧁", "cupcake", "dessert", false},
    {"🍰", "shortcake", "dessert cake", false},
    {"🎂", "birthday cake", "party", false},
    {"🍮", "custard", "dessert", false},
    {"🍭", "lollipop", "candy", false},
    {"🍬", "candy", "sweet", false},
    {"🍫", "chocolate bar", "sweet", false},
    {"🍿", "popcorn", "snack", false},
    {"🍩", "doughnut", "donut", false},
    {"🍪", "cookie", "dessert", false},
    {"🌰", "chestnut", "food", false},
    {"🥜", "peanuts", "food", false},
    {"🍯", "honey pot", "sweet", false},
    {"🥛", "glass of milk", "drink", false},
    {"🍼", "baby bottle", "drink", false},
    {"🫖", "teapot", "tea", false},
    {"☕", "hot beverage", "coffee tea", false},
    {"🍵", "teacup without handle", "tea", false},
    {"🧃", "beverage box", "juice", false},
    {"🥤", "cup with straw", "soda", false},
    {"🧋", "bubble tea", "boba", false},
    {"🍶", "sake", "drink", false},
    {"🍺", "beer mug", "drink alcohol", false},
    {"🍻", "clinking beer mugs", "cheers", false},
    {"🥂", "clinking glasses", "cheers toast", false},
    {"🍷", "wine glass", "drink", false},
    {"🥃", "tumbler glass", "whiskey", false},
    {"🍸", "cocktail glass", "drink", false},
    {"🍹", "tropical drink", "cocktail", false},
    {"🧉", "mate", "drink", false},
    {"🍾", "bottle with popping cork", "champagne", false},
    {"🧊", "ice", "cold", false},
    {"🥄", "spoon", "utensil", false},
    {"🍴", "fork and knife", "eat", false},
    {"🍽️", "fork and knife with plate", "dining", false},
    {"🥣", "bowl with spoon", "cereal", false},
    {"🥡", "takeout box", "food", false},
    {"🥢", "chopsticks", "utensil", false},
    {"🧂", "salt", "food", false},
    {"⚽", "soccer ball", "football sport", false},
    {"🏀", "basketball", "sport", false},
    {"🏈", "american football", "sport", false},
    {"⚾", "baseball", "sport", false},
    {"🥎", "softball", "sport", false},
    {"🎾", "tennis", "sport", false},
    {"🏐", "volleyball", "sport", false},
    {"🏉", "rugby football", "sport", false},
    {"🥏", "flying disc", "frisbee", false},
    {"🎱", "pool 8 ball", "billiards", false},
    {"🪀", "yo-yo", "toy", false},
    {"🏓", "ping pong", "sport", false},
    {"🏸", "badminton", "sport", false},
    {"🏒", "ice hockey", "sport", false},
    {"🏑", "field hockey", "sport", false},
    {"🥍", "lacrosse", "sport", false},
    {"🏏", "cricket game", "sport", false},
    {"🪃", "boomerang", "sport", false},
    {"🥅", "goal net", "sport", false},
    {"⛳", "flag in hole", "golf", false},
    {"🪁", "kite", "fly", false},
    {"🏹", "bow and arrow", "archery", false},
    {"🎣", "fishing pole", "fish", false},
    {"🤿", "diving mask", "scuba", false},
    {"🥊", "boxing glove", "fight", false},
    {"🥋", "martial arts uniform", "karate", false},
    {"🎽", "running shirt", "sport", false},
    {"🛹", "skateboard", "skate", false},
    {"🛼", "roller skate", "skate", false},
    {"🛷", "sled", "snow", false},
    {"⛸️", "ice skate", "hockey", false},
    {"🥌", "curling stone", "sport", false},
    {"🎿", "skis", "snow", false},
    {"⛷️", "skier", "snow", false},
    {"🏂", "snowboarder", "snow", false},
    {"🪂", "parachute", "sky", false},
    {"🏋️", "person lifting weights", "gym", false},
    {"🤼", "people wrestling", "sport", false},
    {"🤸", "person cartwheeling", "gymnast", false},
    {"⛹️", "person bouncing ball", "sport", false},
    {"🤺", "person fencing", "sport", false},
    {"🏇", "horse racing", "sport", false},
    {"⛳", "flag in hole", "golf", false},
    {"🎯", "bullseye", "target dart", false},
    {"🎮", "video game", "controller play", false},
    {"🕹️", "joystick", "game", false},
    {"🎲", "game die", "dice random", false},
    {"🧩", "puzzle piece", "jigsaw", false},
    {"🎭", "performing arts", "theater mask", false},
    {"🎨", "artist palette", "art paint", false},
    {"🎬", "clapper board", "movie film", false},
    {"🎤", "microphone", "sing karaoke", false},
    {"🎧", "headphone", "music", false},
    {"🎼", "musical score", "music", false},
    {"🎹", "musical keyboard", "piano", false},
    {"🥁", "drum", "music", false},
    {"🪘", "long drum", "music", false},
    {"🎷", "saxophone", "music", false},
    {"🎺", "trumpet", "music", false},
    {"🎸", "guitar", "music", false},
    {"🪕", "banjo", "music", false},
    {"🎻", "violin", "music", false},
    {"🪗", "accordion", "music", false},
    {"🎲", "game die", "dice", false},
    {"♟️", "chess pawn", "chess", false},
    {"🎯", "bullseye", "hit", false},
    {"🎳", "bowling", "sport", false},
    {"🎮", "video game", "game", false},
    {"🎰", "slot machine", "casino", false},
    {"🚗", "automobile", "car", false},
    {"🚕", "taxi", "cab", false},
    {"🚙", "sport utility vehicle", "suv car", false},
    {"🚌", "bus", "transit", false},
    {"🚎", "trolleybus", "transit", false},
    {"🏎️", "racing car", "fast", false},
    {"🚓", "police car", "cop", false},
    {"🚑", "ambulance", "emergency", false},
    {"🚒", "fire engine", "truck", false},
    {"🚐", "minibus", "van", false},
    {"🛻", "pickup truck", "truck", false},
    {"🚚", "delivery truck", "truck", false},
    {"🚛", "articulated lorry", "truck", false},
    {"🚜", "tractor", "farm", false},
    {"🦯", "white cane", "blind", false},
    {"🦽", "manual wheelchair", "access", false},
    {"🦼", "motorized wheelchair", "access", false},
    {"🛴", "kick scooter", "scooter", false},
    {"🚲", "bicycle", "bike", false},
    {"🛵", "motor scooter", "vespa", false},
    {"🏍️", "motorcycle", "bike", false},
    {"🛺", "auto rickshaw", "tuk tuk", false},
    {"🚨", "police car light", "siren", false},
    {"🚔", "oncoming police car", "cop", false},
    {"🚍", "oncoming bus", "transit", false},
    {"🚘", "oncoming automobile", "car", false},
    {"🚖", "oncoming taxi", "cab", false},
    {"🚡", "aerial tramway", "cable", false},
    {"🚠", "mountain cableway", "ski", false},
    {"🚟", "suspension railway", "train", false},
    {"🚃", "railway car", "train", false},
    {"🚋", "tram car", "train", false},
    {"🚞", "mountain railway", "train", false},
    {"🚝", "monorail", "train", false},
    {"🚄", "high-speed train", "shinkansen", false},
    {"🚅", "bullet train", "shinkansen", false},
    {"🚈", "light rail", "train", false},
    {"🚂", "locomotive", "train steam", false},
    {"🚆", "train", "rail", false},
    {"🚇", "metro", "subway", false},
    {"🚊", "tram", "transit", false},
    {"🚉", "station", "train", false},
    {"✈️", "airplane", "flight travel", false},
    {"🛫", "airplane departure", "takeoff", false},
    {"🛬", "airplane arrival", "landing", false},
    {"🛩️", "small airplane", "flight", false},
    {"💺", "seat", "plane", false},
    {"🛰️", "satellite", "space", false},
    {"🚀", "rocket", "space launch", false},
    {"🛸", "flying saucer", "ufo", false},
    {"🚁", "helicopter", "flight", false},
    {"🛶", "canoe", "boat", false},
    {"⛵", "sailboat", "boat", false},
    {"🚤", "speedboat", "boat", false},
    {"🛥️", "motor boat", "boat", false},
    {"🛳️", "passenger ship", "cruise", false},
    {"⛴️", "ferry", "boat", false},
    {"🚢", "ship", "boat", false},
    {"⚓", "anchor", "ship", false},
    {"🪝", "hook", "tool", false},
    {"⛽", "fuel pump", "gas", false},
    {"🚧", "construction", "work", false},
    {"🚦", "vertical traffic light", "stop", false},
    {"🚥", "horizontal traffic light", "stop", false},
    {"🚏", "bus stop", "transit", false},
    {"🗺️", "world map", "travel", false},
    {"🗿", "moai", "easter island", false},
    {"🗽", "statue of liberty", "nyc", false},
    {"🗼", "tokyo tower", "japan", false},
    {"🏰", "castle", "building", false},
    {"🏯", "japanese castle", "building", false},
    {"🏟️", "stadium", "sport", false},
    {"🎡", "ferris wheel", "fair", false},
    {"🎢", "roller coaster", "fair", false},
    {"🎠", "carousel horse", "fair", false},
    {"⛲", "fountain", "park", false},
    {"⛱️", "umbrella on ground", "beach", false},
    {"🏖️", "beach with umbrella", "vacation", false},
    {"🏝️", "desert island", "tropical", false},
    {"🏜️", "desert", "sand", false},
    {"🌋", "volcano", "erupt", false},
    {"⛰️", "mountain", "peak", false},
    {"🏔️", "snow-capped mountain", "peak", false},
    {"🗻", "mount fuji", "japan", false},
    {"🏕️", "camping", "tent", false},
    {"⛺", "tent", "camp", false},
    {"🛖", "hut", "house", false},
    {"🏠", "house", "home", false},
    {"🏡", "house with garden", "home", false},
    {"🏘️", "houses", "neighborhood", false},
    {"🏚️", "derelict house", "abandoned", false},
    {"🏗️", "building construction", "crane", false},
    {"🏭", "factory", "industry", false},
    {"🏢", "office building", "work", false},
    {"🏬", "department store", "shop", false},
    {"🏣", "japanese post office", "mail", false},
    {"🏤", "post office", "mail", false},
    {"🏥", "hospital", "health", false},
    {"🏦", "bank", "money", false},
    {"🏨", "hotel", "stay", false},
    {"🏪", "convenience store", "shop", false},
    {"🏫", "school", "education", false},
    {"🏩", "love hotel", "stay", false},
    {"💒", "wedding", "church", false},
    {"🏛️", "classical building", "museum", false},
    {"⛪", "church", "religion", false},
    {"🕌", "mosque", "religion", false},
    {"🕍", "synagogue", "religion", false},
    {"🛕", "hindu temple", "religion", false},
    {"🕋", "kaaba", "mecca", false},
    {"⛩️", "shinto shrine", "japan", false},
    {"⌚", "watch", "time", false},
    {"📱", "mobile phone", "iphone cell", false},
    {"📲", "mobile phone with arrow", "call", false},
    {"💻", "laptop", "computer", false},
    {"⌨️", "keyboard", "type", false},
    {"🖥️", "desktop computer", "pc", false},
    {"🖨️", "printer", "print", false},
    {"🖱️", "computer mouse", "click", false},
    {"🖲️", "trackball", "mouse", false},
    {"🕹️", "joystick", "game", false},
    {"🗜️", "clamp", "tool", false},
    {"💽", "computer disk", "minidisc", false},
    {"💾", "floppy disk", "save", false},
    {"💿", "optical disk", "cd", false},
    {"📀", "dvd", "disk", false},
    {"📼", "videocassette", "vhs", false},
    {"📷", "camera", "photo", false},
    {"📸", "camera with flash", "photo", false},
    {"📹", "video camera", "film", false},
    {"🎥", "movie camera", "film", false},
    {"📽️", "film projector", "movie", false},
    {"🎞️", "film frames", "movie", false},
    {"📞", "telephone receiver", "call", false},
    {"☎️", "telephone", "call", false},
    {"📟", "pager", "beeper", false},
    {"📠", "fax machine", "fax", false},
    {"📺", "television", "tv", false},
    {"📻", "radio", "music", false},
    {"🎙️", "studio microphone", "podcast", false},
    {"🎚️", "level slider", "audio", false},
    {"🎛️", "control knobs", "mixer", false},
    {"🧭", "compass", "navigate", false},
    {"⏱️", "stopwatch", "timer", false},
    {"⏲️", "timer clock", "kitchen", false},
    {"⏰", "alarm clock", "wake", false},
    {"🕰️", "mantelpiece clock", "time", false},
    {"⌛", "hourglass done", "wait", false},
    {"⏳", "hourglass not done", "loading", false},
    {"📡", "satellite antenna", "signal", false},
    {"🔋", "battery", "power", false},
    {"🔌", "electric plug", "power", false},
    {"💡", "light bulb", "idea", false},
    {"🔦", "flashlight", "torch", false},
    {"🕯️", "candle", "light", false},
    {"🪔", "diya lamp", "light", false},
    {"🧯", "fire extinguisher", "safety", false},
    {"🛢️", "oil drum", "barrel", false},
    {"💸", "money with wings", "spend", false},
    {"💵", "dollar banknote", "money usd", false},
    {"💴", "yen banknote", "money jpy", false},
    {"💶", "euro banknote", "money eur", false},
    {"💷", "pound banknote", "money gbp", false},
    {"🪙", "coin", "money", false},
    {"💰", "money bag", "rich", false},
    {"💳", "credit card", "pay", false},
    {"💎", "gem stone", "diamond", false},
    {"⚖️", "balance scale", "law justice", false},
    {"🪜", "ladder", "climb", false},
    {"🧰", "toolbox", "tools", false},
    {"🪛", "screwdriver", "tool", false},
    {"🔧", "wrench", "tool", false},
    {"🔨", "hammer", "tool", false},
    {"⚒️", "hammer and pick", "tool", false},
    {"🛠️", "hammer and wrench", "tool", false},
    {"⛏️", "pick", "mine", false},
    {"🪚", "carpentry saw", "tool", false},
    {"🔩", "nut and bolt", "hardware", false},
    {"⚙️", "gear", "settings", false},
    {"🪤", "mouse trap", "trap", false},
    {"🧱", "brick", "wall", false},
    {"⛓️", "chains", "link", false},
    {"🧲", "magnet", "attract", false},
    {"🔫", "pistol", "gun water", false},
    {"💣", "bomb", "explode", false},
    {"🧨", "firecracker", "explode", false},
    {"🪓", "axe", "tool", false},
    {"🔪", "kitchen knife", "cut", false},
    {"🗡️", "dagger", "sword", false},
    {"⚔️", "crossed swords", "fight", false},
    {"🛡️", "shield", "protect", false},
    {"🚬", "cigarette", "smoke", false},
    {"⚰️", "coffin", "death", false},
    {"🪦", "headstone", "grave", false},
    {"⚱️", "funeral urn", "death", false},
    {"🏺", "amphora", "vase", false},
    {"🔮", "crystal ball", "magic future", false},
    {"📿", "prayer beads", "religion", false},
    {"🧿", "nazar amulet", "evil eye", false},
    {"💈", "barber pole", "haircut", false},
    {"⚗️", "alembic", "science", false},
    {"🔭", "telescope", "space", false},
    {"🔬", "microscope", "science", false},
    {"🕳️", "hole", "empty", false},
    {"🩹", "adhesive bandage", "bandaid", false},
    {"🩺", "stethoscope", "doctor", false},
    {"💊", "pill", "medicine", false},
    {"💉", "syringe", "shot vaccine", false},
    {"🩸", "drop of blood", "donate", false},
    {"🧬", "dna", "science", false},
    {"🦠", "microbe", "virus germ", false},
    {"🧫", "petri dish", "science", false},
    {"🧪", "test tube", "science", false},
    {"🌡️", "thermometer", "temperature", false},
    {"🧹", "broom", "clean", false},
    {"🪠", "plunger", "toilet", false},
    {"🧺", "basket", "laundry", false},
    {"🧻", "roll of paper", "toilet", false},
    {"🚽", "toilet", "bathroom", false},
    {"🚰", "potable water", "drink", false},
    {"🚿", "shower", "bath", false},
    {"🛁", "bathtub", "bath", false},
    {"🛀", "person taking bath", "bath", false},
    {"🧼", "soap", "clean", false},
    {"🪥", "toothbrush", "clean", false},
    {"🪒", "razor", "shave", false},
    {"🧽", "sponge", "clean", false},
    {"🧴", "lotion bottle", "soap", false},
    {"🛎️", "bellhop bell", "hotel", false},
    {"🔑", "key", "lock", false},
    {"🗝️", "old key", "lock", false},
    {"🚪", "door", "enter", false},
    {"🪑", "chair", "sit", false},
    {"🛋️", "couch and lamp", "sofa", false},
    {"🛏️", "bed", "sleep", false},
    {"🛌", "person in bed", "sleep", false},
    {"🧸", "teddy bear", "toy", false},
    {"🪆", "nesting dolls", "matryoshka", false},
    {"🖼️", "framed picture", "art", false},
    {"🪞", "mirror", "reflect", false},
    {"🪟", "window", "view", false},
    {"🛍️", "shopping bags", "buy", false},
    {"🛒", "shopping cart", "buy", false},
    {"🎁", "wrapped gift", "present", false},
    {"🎈", "balloon", "party", false},
    {"🎏", "carp streamer", "koinobori", false},
    {"🎀", "ribbon", "bow", false},
    {"🪄", "magic wand", "magic", false},
    {"🪅", "pinata", "party", false},
    {"🎊", "confetti ball", "party", false},
    {"🎉", "party popper", "celebrate", false},
    {"🎎", "japanese dolls", "hinamatsuri", false},
    {"🏮", "red paper lantern", "izakaya", false},
    {"🎐", "wind chime", "summer", false},
    {"🧧", "red envelope", "luck money", false},
    {"✉️", "envelope", "mail", false},
    {"📩", "envelope with arrow", "mail", false},
    {"📨", "incoming envelope", "mail", false},
    {"📧", "e-mail", "email", false},
    {"💌", "love letter", "mail", false},
    {"📥", "inbox tray", "mail", false},
    {"📤", "outbox tray", "mail", false},
    {"📦", "package", "box shipping", false},
    {"🏷️", "label", "tag", false},
    {"🪧", "placard", "sign", false},
    {"📪", "closed mailbox with lowered flag", "mail", false},
    {"📫", "closed mailbox with raised flag", "mail", false},
    {"📬", "open mailbox with raised flag", "mail", false},
    {"📭", "open mailbox with lowered flag", "mail", false},
    {"📮", "postbox", "mail", false},
    {"📯", "postal horn", "mail", false},
    {"📜", "scroll", "document", false},
    {"📃", "page with curl", "document", false},
    {"📄", "page facing up", "document", false},
    {"📑", "bookmark tabs", "document", false},
    {"🧾", "receipt", "bill", false},
    {"📊", "bar chart", "stats", false},
    {"📈", "chart increasing", "growth", false},
    {"📉", "chart decreasing", "loss", false},
    {"🗒️", "spiral notepad", "notes", false},
    {"🗓️", "spiral calendar", "date", false},
    {"📆", "tear-off calendar", "date", false},
    {"📅", "calendar", "date", false},
    {"🗑️", "wastebasket", "trash delete", false},
    {"📇", "card index", "contacts", false},
    {"🗃️", "card file box", "archive", false},
    {"🗳️", "ballot box with ballot", "vote", false},
    {"🗄️", "file cabinet", "office", false},
    {"📋", "clipboard", "copy", false},
    {"📁", "file folder", "directory", false},
    {"📂", "open file folder", "directory", false},
    {"🗂️", "card index dividers", "files", false},
    {"🗞️", "rolled-up newspaper", "news", false},
    {"📰", "newspaper", "news", false},
    {"📓", "notebook", "notes", false},
    {"📔", "notebook with decorative cover", "notes", false},
    {"📒", "ledger", "book", false},
    {"📕", "closed book", "read", false},
    {"📗", "green book", "read", false},
    {"📘", "blue book", "read", false},
    {"📙", "orange book", "read", false},
    {"📚", "books", "library", false},
    {"📖", "open book", "read", false},
    {"🔖", "bookmark", "save", false},
    {"🧷", "safety pin", "clip", false},
    {"🔗", "link", "url chain", false},
    {"📎", "paperclip", "attach", false},
    {"🖇️", "linked paperclips", "attach", false},
    {"📐", "triangular ruler", "math", false},
    {"📏", "straight ruler", "measure", false},
    {"🧮", "abacus", "math", false},
    {"📌", "pushpin", "pin", false},
    {"📍", "round pushpin", "location", false},
    {"✂️", "scissors", "cut", false},
    {"🖊️", "pen", "write", false},
    {"🖋️", "fountain pen", "write", false},
    {"✒️", "black nib", "write", false},
    {"🖌️", "paintbrush", "art", false},
    {"🖍️", "crayon", "draw", false},
    {"📝", "memo", "note write", false},
    {"✏️", "pencil", "write", false},
    {"🔍", "magnifying glass tilted left", "search", false},
    {"🔎", "magnifying glass tilted right", "search", false},
    {"🔏", "locked with pen", "secure", false},
    {"🔐", "locked with key", "secure", false},
    {"🔒", "locked", "security", false},
    {"🔓", "unlocked", "open", false},
    {"❤️", "red heart", "love", false},
    {"🧡", "orange heart", "love", false},
    {"💛", "yellow heart", "love", false},
    {"💚", "green heart", "love", false},
    {"💙", "blue heart", "love", false},
    {"💜", "purple heart", "love", false},
    {"🖤", "black heart", "love", false},
    {"🤍", "white heart", "love", false},
    {"🤎", "brown heart", "love", false},
    {"💔", "broken heart", "sad", false},
    {"❣️", "heart exclamation", "love", false},
    {"💕", "two hearts", "love", false},
    {"💞", "revolving hearts", "love", false},
    {"💓", "beating heart", "love", false},
    {"💗", "growing heart", "love", false},
    {"💖", "sparkling heart", "love", false},
    {"💘", "heart with arrow", "love", false},
    {"💝", "heart with ribbon", "love", false},
    {"💟", "heart decoration", "love", false},
    {"☮️", "peace symbol", "peace", false},
    {"✝️", "latin cross", "christian", false},
    {"☪️", "star and crescent", "islam", false},
    {"🕉️", "om", "hindu", false},
    {"☸️", "wheel of dharma", "buddhist", false},
    {"✡️", "star of david", "jewish", false},
    {"🔯", "dotted six-pointed star", "star", false},
    {"🕎", "menorah", "jewish", false},
    {"☯️", "yin yang", "balance", false},
    {"☦️", "orthodox cross", "christian", false},
    {"🛐", "place of worship", "religion", false},
    {"⛎", "ophiuchus", "zodiac", false},
    {"♈", "aries", "zodiac", false},
    {"♉", "taurus", "zodiac", false},
    {"♊", "gemini", "zodiac", false},
    {"♋", "cancer", "zodiac", false},
    {"♌", "leo", "zodiac", false},
    {"♍", "virgo", "zodiac", false},
    {"♎", "libra", "zodiac", false},
    {"♏", "scorpio", "zodiac", false},
    {"♐", "sagittarius", "zodiac", false},
    {"♑", "capricorn", "zodiac", false},
    {"♒", "aquarius", "zodiac", false},
    {"♓", "pisces", "zodiac", false},
    {"🆔", "id button", "identity", false},
    {"⚛️", "atom symbol", "science", false},
    {"🉑", "japanese acceptable button", "ok", false},
    {"☢️", "radioactive", "nuclear", false},
    {"☣️", "biohazard", "danger", false},
    {"📴", "mobile phone off", "silent", false},
    {"📳", "vibration mode", "phone", false},
    {"🈶", "japanese not free of charge", "kanji", false},
    {"🈚", "japanese free of charge", "kanji", false},
    {"🈸", "japanese application", "kanji", false},
    {"🈺", "japanese open for business", "kanji", false},
    {"🈷️", "japanese monthly amount", "kanji", false},
    {"✴️", "eight-pointed star", "star", false},
    {"🆚", "vs button", "versus", false},
    {"💮", "white flower", "well done", false},
    {"🉐", "japanese bargain", "kanji", false},
    {"㊙️", "japanese secret", "kanji", false},
    {"㊗️", "japanese congratulations", "kanji", false},
    {"🈴", "japanese passing grade", "kanji", false},
    {"🈵", "japanese no vacancy", "kanji", false},
    {"🈹", "japanese discount", "kanji", false},
    {"🈲", "japanese prohibited", "kanji", false},
    {"🅰️", "a button", "blood", false},
    {"🅱️", "b button", "blood", false},
    {"🆎", "ab button", "blood", false},
    {"🆑", "cl button", "clear", false},
    {"🅾️", "o button", "blood", false},
    {"🆘", "sos button", "help emergency", false},
    {"❌", "cross mark", "x no", false},
    {"⭕", "hollow red circle", "o yes", false},
    {"🛑", "stop sign", "halt", false},
    {"⛔", "no entry", "stop", false},
    {"📛", "name badge", "tag", false},
    {"🚫", "prohibited", "ban", false},
    {"💯", "hundred points", "100", false},
    {"💢", "anger symbol", "mad", false},
    {"♨️", "hot springs", "onsen", false},
    {"🚷", "no pedestrians", "ban", false},
    {"🚯", "no littering", "ban", false},
    {"🚳", "no bicycles", "ban", false},
    {"🚱", "non-potable water", "ban", false},
    {"🔞", "no one under eighteen", "nsfw", false},
    {"📵", "no mobile phones", "ban", false},
    {"🚭", "no smoking", "ban", false},
    {"❗", "exclamation mark", "bang", false},
    {"❕", "white exclamation mark", "bang", false},
    {"❓", "question mark", "help", false},
    {"❔", "white question mark", "help", false},
    {"‼️", "double exclamation mark", "bang", false},
    {"⁉️", "exclamation question mark", "interrobang", false},
    {"🔅", "dim button", "brightness", false},
    {"🔆", "bright button", "brightness", false},
    {"〽️", "part alternation mark", "music", false},
    {"⚠️", "warning", "caution", false},
    {"🚸", "children crossing", "school", false},
    {"🔱", "trident emblem", "poseidon", false},
    {"⚜️", "fleur-de-lis", "france", false},
    {"🔰", "japanese symbol for beginner", "leaf", false},
    {"♻️", "recycling symbol", "recycle", false},
    {"✅", "check mark button", "done yes ok", false},
    {"🈯", "japanese reserved button", "kanji", false},
    {"💹", "chart increasing with yen", "market", false},
    {"❇️", "sparkle", "star", false},
    {"✳️", "eight-spoked asterisk", "star", false},
    {"❎", "cross mark button", "x", false},
    {"🌐", "globe with meridians", "www internet", false},
    {"💠", "diamond with a dot", "shape", false},
    {"Ⓜ️", "circled m", "metro", false},
    {"🌀", "cyclone", "swirl", false},
    {"💤", "zzz", "sleep", false},
    {"🏧", "atm sign", "bank", false},
    {"🚾", "water closet", "restroom wc", false},
    {"♿", "wheelchair symbol", "access", false},
    {"🅿️", "p button", "parking", false},
    {"🛗", "elevator", "lift", false},
    {"🈳", "japanese vacancy button", "kanji", false},
    {"🈂️", "japanese service charge", "sa", false},
    {"🛂", "passport control", "travel", false},
    {"🛃", "customs", "travel", false},
    {"🛄", "baggage claim", "travel", false},
    {"🛅", "left luggage", "travel", false},
    {"🚹", "mens room", "restroom", false},
    {"🚺", "womens room", "restroom", false},
    {"🚼", "baby symbol", "restroom", false},
    {"⚧️", "transgender symbol", "pride", false},
    {"🚻", "restroom", "bathroom", false},
    {"🚮", "litter in bin sign", "trash", false},
    {"🎦", "cinema", "movie", false},
    {"📶", "antenna bars", "signal wifi", false},
    {"🈁", "japanese here button", "koko", false},
    {"🔣", "input symbols", "signs", false},
    {"ℹ️", "information", "info", false},
    {"🔤", "input latin letters", "abc", false},
    {"🔡", "input latin lowercase", "abcd", false},
    {"🔠", "input latin uppercase", "abcd", false},
    {"🔢", "input numbers", "1234", false},
    {"🔟", "keycap 10", "ten", false},
    {"#️⃣", "keycap #", "hash", false},
    {"*️⃣", "keycap *", "star", false},
    {"0️⃣", "keycap 0", "zero", false},
    {"1️⃣", "keycap 1", "one", false},
    {"2️⃣", "keycap 2", "two", false},
    {"3️⃣", "keycap 3", "three", false},
    {"4️⃣", "keycap 4", "four", false},
    {"5️⃣", "keycap 5", "five", false},
    {"6️⃣", "keycap 6", "six", false},
    {"7️⃣", "keycap 7", "seven", false},
    {"8️⃣", "keycap 8", "eight", false},
    {"9️⃣", "keycap 9", "nine", false},
    {"🔙", "back arrow", "return", false},
    {"🔚", "end arrow", "stop", false},
    {"🔛", "on arrow", "power", false},
    {"🔜", "soon arrow", "later", false},
    {"🔝", "top arrow", "up", false},
    {"▶️", "play button", "media", false},
    {"⏸️", "pause button", "media", false},
    {"⏯️", "play or pause button", "media", false},
    {"⏹️", "stop button", "media", false},
    {"⏺️", "record button", "media", false},
    {"⏭️", "next track button", "media", false},
    {"⏮️", "last track button", "media", false},
    {"⏩", "fast-forward button", "media", false},
    {"⏪", "fast reverse button", "media", false},
    {"⏫", "fast up button", "media", false},
    {"⏬", "fast down button", "media", false},
    {"◀️", "reverse button", "media", false},
    {"🔼", "upwards button", "up", false},
    {"🔽", "downwards button", "down", false},
    {"➡️", "right arrow", "next", false},
    {"⬅️", "left arrow", "back", false},
    {"⬆️", "up arrow", "north", false},
    {"⬇️", "down arrow", "south", false},
    {"↗️", "up-right arrow", "ne", false},
    {"↘️", "down-right arrow", "se", false},
    {"↙️", "down-left arrow", "sw", false},
    {"↖️", "up-left arrow", "nw", false},
    {"↕️", "up-down arrow", "vertical", false},
    {"↔️", "left-right arrow", "horizontal", false},
    {"↪️", "left arrow curving right", "redo", false},
    {"↩️", "right arrow curving left", "undo", false},
    {"⤴️", "right arrow curving up", "up", false},
    {"⤵️", "right arrow curving down", "down", false},
    {"🔀", "shuffle tracks button", "random", false},
    {"🔁", "repeat button", "loop", false},
    {"🔂", "repeat single button", "loop", false},
    {"🔄", "counterclockwise arrows button", "refresh reload", false},
    {"🔃", "clockwise vertical arrows", "reload", false},
    {"🎵", "musical note", "song", false},
    {"🎶", "musical notes", "song", false},
    {"➕", "plus", "add", false},
    {"➖", "minus", "subtract", false},
    {"➗", "divide", "math", false},
    {"✖️", "multiply", "math", false},
    {"♾️", "infinity", "forever", false},
    {"💲", "heavy dollar sign", "money", false},
    {"💱", "currency exchange", "money fx", false},
    {"™️", "trade mark", "tm", false},
    {"©️", "copyright", "legal", false},
    {"®️", "registered", "legal", false},
    {"〰️", "wavy dash", "line", false},
    {"➰", "curly loop", "loop", false},
    {"➿", "double curly loop", "loop", false},
    {"🔚", "end arrow", "end", false},
    {"🔙", "back arrow", "back", false},
    {"🔛", "on! arrow", "on", false},
    {"🔝", "top arrow", "top", false},
    {"✔️", "check mark", "done yes", false},
    {"☑️", "check box with check", "todo", false},
    {"🔘", "radio button", "select", false},
    {"🔴", "red circle", "dot", false},
    {"🟠", "orange circle", "dot", false},
    {"🟡", "yellow circle", "dot", false},
    {"🟢", "green circle", "dot", false},
    {"🔵", "blue circle", "dot", false},
    {"🟣", "purple circle", "dot", false},
    {"⚫", "black circle", "dot", false},
    {"⚪", "white circle", "dot", false},
    {"🟤", "brown circle", "dot", false},
    {"🔺", "red triangle pointed up", "up", false},
    {"🔻", "red triangle pointed down", "down", false},
    {"🔸", "small orange diamond", "shape", false},
    {"🔹", "small blue diamond", "shape", false},
    {"🔶", "large orange diamond", "shape", false},
    {"🔷", "large blue diamond", "shape", false},
    {"🔳", "white square button", "shape", false},
    {"🔲", "black square button", "shape", false},
    {"▪️", "black small square", "shape", false},
    {"▫️", "white small square", "shape", false},
    {"◾", "black medium-small square", "shape", false},
    {"◽", "white medium-small square", "shape", false},
    {"◼️", "black medium square", "shape", false},
    {"◻️", "white medium square", "shape", false},
    {"🟥", "red square", "shape", false},
    {"🟧", "orange square", "shape", false},
    {"🟨", "yellow square", "shape", false},
    {"🟩", "green square", "shape", false},
    {"🟦", "blue square", "shape", false},
    {"🟪", "purple square", "shape", false},
    {"⬛", "black large square", "shape", false},
    {"⬜", "white large square", "shape", false},
    {"🟫", "brown square", "shape", false},
    {"🔈", "speaker low volume", "sound", false},
    {"🔇", "muted speaker", "mute", false},
    {"🔉", "speaker medium volume", "sound", false},
    {"🔊", "speaker high volume", "loud", false},
    {"🔔", "bell", "notify", false},
    {"🔕", "bell with slash", "mute", false},
    {"📣", "megaphone", "announce", false},
    {"📢", "loudspeaker", "announce", false},
    {"👁️‍🗨️", "eye in speech bubble", "witness", false},
    {"💬", "speech balloon", "comment chat", false},
    {"💭", "thought balloon", "think", false},
    {"🗯️", "right anger bubble", "mad", false},
    {"♠️", "spade suit", "cards", false},
    {"♣️", "club suit", "cards", false},
    {"♥️", "heart suit", "cards", false},
    {"♦️", "diamond suit", "cards", false},
    {"🃏", "joker", "cards", false},
    {"🎴", "flower playing cards", "hanafuda", false},
    {"🀄", "mahjong red dragon", "game", false},
    {"🕐", "one oclock", "time clock", false},
    {"🕑", "two oclock", "time clock", false},
    {"🕒", "three oclock", "time clock", false},
    {"🕓", "four oclock", "time clock", false},
    {"🕔", "five oclock", "time clock", false},
    {"🕕", "six oclock", "time clock", false},
    {"🕖", "seven oclock", "time clock", false},
    {"🕗", "eight oclock", "time clock", false},
    {"🕘", "nine oclock", "time clock", false},
    {"🕙", "ten oclock", "time clock", false},
    {"🕚", "eleven oclock", "time clock", false},
    {"🕛", "twelve oclock", "time clock", false},
    {"🏳️", "white flag", "surrender", false},
    {"🏴", "black flag", "pirate", false},
    {"🏁", "chequered flag", "race finish", false},
    {"🚩", "triangular flag", "mark", false},
    {"🏳️‍🌈", "rainbow flag", "pride lgbt", false},
    {"🏳️‍⚧️", "transgender flag", "pride", false},
    {"🏴‍☠️", "pirate flag", "jolly roger", false},
    {"🇺🇸", "flag united states", "usa us america", false},
    {"🇬🇧", "flag united kingdom", "uk britain england", false},
    {"🇨🇦", "flag canada", "canada", false},
    {"🇦🇺", "flag australia", "australia", false},
    {"🇩🇪", "flag germany", "germany", false},
    {"🇫🇷", "flag france", "france", false},
    {"🇯🇵", "flag japan", "japan", false},
    {"🇰🇷", "flag south korea", "korea", false},
    {"🇨🇳", "flag china", "china", false},
    {"🇮🇳", "flag india", "india", false},
    {"🇧🇷", "flag brazil", "brazil", false},
    {"🇲🇽", "flag mexico", "mexico", false},
    {"🇪🇸", "flag spain", "spain", false},
    {"🇮🇹", "flag italy", "italy", false},
    {"🇳🇱", "flag netherlands", "holland dutch", false},
    {"🇸🇪", "flag sweden", "sweden", false},
    {"🇳🇴", "flag norway", "norway", false},
    {"🇩🇰", "flag denmark", "denmark", false},
    {"🇫🇮", "flag finland", "finland", false},
    {"🇵🇱", "flag poland", "poland", false},
    {"🇺🇦", "flag ukraine", "ukraine", false},
    {"🇮🇪", "flag ireland", "ireland", false},
    {"🇳🇿", "flag new zealand", "kiwi", false},
    {"🇨🇭", "flag switzerland", "swiss", false},
    {"🇦🇹", "flag austria", "austria", false},
    {"🇧🇪", "flag belgium", "belgium", false},
    {"🇵🇹", "flag portugal", "portugal", false},
    {"🇬🇷", "flag greece", "greece", false},
    {"🇹🇷", "flag turkey", "turkey", false},
    {"🇸🇦", "flag saudi arabia", "saudi", false},
    {"🇦🇪", "flag united arab emirates", "uae dubai", false},
    {"🇸🇬", "flag singapore", "singapore", false},
    {"🇭🇰", "flag hong kong", "hk", false},
    {"🇹🇼", "flag taiwan", "taiwan", false},
    {"🇹🇭", "flag thailand", "thailand", false},
    {"🇻🇳", "flag vietnam", "vietnam", false},
    {"🇵🇭", "flag philippines", "philippines", false},
    {"🇮🇩", "flag indonesia", "indonesia", false},
    {"🇲🇾", "flag malaysia", "malaysia", false},
    {"🇿🇦", "flag south africa", "rsa", false},
    {"🇳🇬", "flag nigeria", "nigeria", false},
    {"🇪🇬", "flag egypt", "egypt", false},
    {"🇮🇱", "flag israel", "israel", false},
    {"🇷🇺", "flag russia", "russia", false},
    {"🇦🇷", "flag argentina", "argentina", false},
    {"🇨🇱", "flag chile", "chile", false},
    {"🇨🇴", "flag colombia", "colombia", false},
    {"🇵🇪", "flag peru", "peru", false},
    {"🇪🇺", "flag european union", "eu europe", false},
    {"🇺🇳", "flag united nations", "un", false},
    // Symbols / punctuation / math / currency (copy as characters)
    {"→", "rightwards arrow", "arrow next", true},
    {"←", "leftwards arrow", "arrow back", true},
    {"↑", "upwards arrow", "arrow", true},
    {"↓", "downwards arrow", "arrow", true},
    {"↔", "left right arrow", "arrow", true},
    {"↕", "up down arrow", "arrow", true},
    {"⇒", "rightwards double arrow", "implies", true},
    {"⇐", "leftwards double arrow", "implied by", true},
    {"⇔", "left right double arrow", "iff equivalent", true},
    {"↩", "rightwards arrow with hook", "return enter", true},
    {"↪", "leftwards arrow with hook", "redo", true},
    {"↵", "downwards arrow with corner leftwards", "return enter", true},
    {"↻", "clockwise open circle arrow", "refresh reload", true},
    {"↺", "anticlockwise open circle arrow", "undo", true},
    {"«", "left double angle quote", "guillemet", true},
    {"»", "right double angle quote", "guillemet", true},
    {"‹", "single left angle quote", "quote", true},
    {"›", "single right angle quote", "quote", true},
    {"“", "left double quotation mark", "quote", true},
    {"”", "right double quotation mark", "quote", true},
    {"‘", "left single quotation mark", "quote", true},
    {"’", "right single quotation mark apostrophe", "quote", true},
    {"–", "en dash", "dash", true},
    {"—", "em dash", "dash", true},
    {"…", "ellipsis", "dots", true},
    {"•", "bullet", "dot list", true},
    {"·", "middle dot", "interpunct", true},
    {"°", "degree", "angle temperature", true},
    {"′", "prime", "feet minutes", true},
    {"″", "double prime", "inches seconds", true},
    {"‰", "per mille", "permille", true},
    {"‱", "per ten thousand", "basis point", true},
    {"©", "copyright", "legal", true},
    {"®", "registered", "legal", true},
    {"™", "trademark", "tm legal", true},
    {"§", "section", "legal", true},
    {"¶", "pilcrow paragraph", "legal", true},
    {"†", "dagger", "footnote", true},
    {"‡", "double dagger", "footnote", true},
    {"★", "black star", "star", true},
    {"☆", "white star", "star", true},
    {"♠", "spade", "cards", true},
    {"♣", "club", "cards", true},
    {"♥", "heart", "cards", true},
    {"♦", "diamond", "cards", true},
    {"✓", "check", "tick yes done", true},
    {"✔", "heavy check", "tick yes", true},
    {"✗", "ballot x", "cross no", true},
    {"✘", "heavy ballot x", "cross no", true},
    {"☐", "ballot box", "checkbox empty", true},
    {"☑", "ballot box with check", "checkbox", true},
    {"☒", "ballot box with x", "checkbox", true},
    {"★", "black star", "favorite", true},
    {"○", "white circle", "ring", true},
    {"●", "black circle", "dot", true},
    {"□", "white square", "box", true},
    {"■", "black square", "box", true},
    {"△", "white up-pointing triangle", "delta", true},
    {"▲", "black up-pointing triangle", "play", true},
    {"▽", "white down-pointing triangle", "nabla", true},
    {"▼", "black down-pointing triangle", "dropdown", true},
    {"◁", "white left-pointing triangle", "shape", true},
    {"▶", "black right-pointing triangle", "play", true},
    {"◀", "black left-pointing triangle", "back", true},
    {"◆", "black diamond", "shape", true},
    {"◇", "white diamond", "shape", true},
    {"★", "star", "shape", true},
    {"∞", "infinity", "math forever", true},
    {"≈", "almost equal", "approx math", true},
    {"≠", "not equal", "math", true},
    {"≤", "less than or equal", "math lte", true},
    {"≥", "greater than or equal", "math gte", true},
    {"±", "plus minus", "math", true},
    {"∓", "minus plus", "math", true},
    {"×", "multiplication sign", "times math", true},
    {"÷", "division sign", "math", true},
    {"·", "dot operator", "math", true},
    {"√", "square root", "math radical", true},
    {"∛", "cube root", "math", true},
    {"∑", "n-ary summation", "sum math", true},
    {"∏", "n-ary product", "math", true},
    {"∫", "integral", "math calculus", true},
    {"∮", "contour integral", "math", true},
    {"∂", "partial differential", "math", true},
    {"∇", "nabla", "del math", true},
    {"∆", "increment", "delta math", true},
    {"∝", "proportional to", "math", true},
    {"∈", "element of", "set math", true},
    {"∉", "not an element of", "set math", true},
    {"∋", "contains as member", "set math", true},
    {"∩", "intersection", "set math", true},
    {"∪", "union", "set math", true},
    {"⊂", "subset of", "set math", true},
    {"⊃", "superset of", "set math", true},
    {"⊆", "subset of or equal to", "set math", true},
    {"⊇", "superset of or equal to", "set math", true},
    {"∅", "empty set", "null math", true},
    {"∀", "for all", "math logic", true},
    {"∃", "there exists", "math logic", true},
    {"∄", "there does not exist", "math logic", true},
    {"∧", "logical and", "math", true},
    {"∨", "logical or", "math", true},
    {"¬", "not sign", "math logic", true},
    {"⊕", "circled plus", "xor math", true},
    {"⊗", "circled times", "math", true},
    {"⊥", "up tack", "perpendicular math", true},
    {"⊤", "down tack", "true math", true},
    {"⊢", "right tack", "proves math", true},
    {"∴", "therefore", "math", true},
    {"∵", "because", "math", true},
    {"∶", "ratio", "math", true},
    {"∷", "proportion", "math", true},
    {"π", "pi", "math greek", true},
    {"Π", "capital pi", "math greek", true},
    {"Σ", "capital sigma", "math greek", true},
    {"σ", "sigma", "math greek", true},
    {"μ", "mu", "micro greek", true},
    {"Ω", "omega", "ohm greek", true},
    {"ω", "small omega", "greek", true},
    {"α", "alpha", "greek", true},
    {"β", "beta", "greek", true},
    {"γ", "gamma", "greek", true},
    {"δ", "delta", "greek", true},
    {"ε", "epsilon", "greek", true},
    {"θ", "theta", "greek", true},
    {"λ", "lambda", "greek", true},
    {"φ", "phi", "greek", true},
    {"ψ", "psi", "greek", true},
    {"τ", "tau", "greek", true},
    {"ρ", "rho", "greek", true},
    {"η", "eta", "greek", true},
    {"ξ", "xi", "greek", true},
    {"ζ", "zeta", "greek", true},
    {"κ", "kappa", "greek", true},
    {"ν", "nu", "greek", true},
    {"χ", "chi", "greek", true},
    {"ℓ", "script l", "liter math", true},
    {"ℏ", "h bar", "planck physics", true},
    {"Å", "angstrom", "unit", true},
    {"℃", "degree celsius", "temperature", true},
    {"℉", "degree fahrenheit", "temperature", true},
    {"µ", "micro sign", "si", true},
    {"Ω", "ohm", "resistance", true},
    {"$", "dollar sign", "currency usd money", true},
    {"¢", "cent sign", "currency", true},
    {"£", "pound sign", "currency gbp", true},
    {"¤", "currency sign", "money", true},
    {"¥", "yen sign", "currency jpy cny", true},
    {"€", "euro sign", "currency eur", true},
    {"₹", "indian rupee", "currency inr", true},
    {"₩", "won sign", "currency krw", true},
    {"₽", "ruble sign", "currency rub", true},
    {"₺", "turkish lira", "currency try", true},
    {"₦", "naira sign", "currency ngn", true},
    {"₱", "peso sign", "currency php", true},
    {"₪", "new shekel", "currency ils", true},
    {"₫", "dong sign", "currency vnd", true},
    {"₴", "hryvnia", "currency uah", true},
    {"฿", "baht", "currency thb", true},
    {"₡", "colon sign", "currency crc", true},
    {"₵", "cedi", "currency ghs", true},
    {"₸", "tenge", "currency kzt", true},
    {"₺", "lira", "currency", true},
    {"₼", "manat", "currency azn", true},
    {"₾", "lari", "currency gel", true},
    {"₿", "bitcoin", "currency btc crypto", true},
    {"№", "numero", "number", true},
    {"℅", "care of", "address", true},
    {"ℓ", "liter symbol", "volume", true},
    {"℮", "estimated symbol", "packaging", true},
    {"←", "left arrow", "nav", true},
    {"→", "right arrow", "nav", true},
    {"↑", "up arrow", "nav", true},
    {"↓", "down arrow", "nav", true},
    {"⌂", "house", "home", true},
    {"⌘", "command", "mac apple", true},
    {"⌥", "option", "mac alt", true},
    {"⇧", "shift", "keyboard", true},
    {"⌃", "control", "keyboard ctrl", true},
    {"⎋", "escape", "keyboard esc", true},
    {"⇥", "tab", "keyboard", true},
    {"⌫", "delete", "backspace keyboard", true},
    {"⌦", "forward delete", "keyboard", true},
    {"⏎", "return", "enter keyboard", true},
    {"␣", "open box space", "spacebar", true},
    {"⏻", "power", "on off", true},
    {"⏼", "power on-off", "standby", true},
    {"⭘", "power off", "standby", true},
    {"⏽", "power on", "standby", true},
    {"☀", "black sun with rays", "weather", true},
    {"☁", "cloud", "weather", true},
    {"☂", "umbrella", "weather", true},
    {"☃", "snowman", "weather", true},
    {"☄", "comet", "space", true},
    {"☎", "black telephone", "phone", true},
    {"☑", "ballot box with check", "todo", true},
    {"☒", "ballot box with x", "todo", true},
    {"♂", "male sign", "gender", true},
    {"♀", "female sign", "gender", true},
    {"⚲", "neuter", "gender", true},
    {"♔", "white chess king", "chess", true},
    {"♕", "white chess queen", "chess", true},
    {"♖", "white chess rook", "chess", true},
    {"♗", "white chess bishop", "chess", true},
    {"♘", "white chess knight", "chess", true},
    {"♙", "white chess pawn", "chess", true},
    {"♚", "black chess king", "chess", true},
    {"♛", "black chess queen", "chess", true},
    {"♜", "black chess rook", "chess", true},
    {"♝", "black chess bishop", "chess", true},
    {"♞", "black chess knight", "chess", true},
    {"♟", "black chess pawn", "chess", true},
    {"♩", "quarter note", "music", true},
    {"♪", "eighth note", "music", true},
    {"♫", "beamed eighth notes", "music", true},
    {"♬", "beamed sixteenth notes", "music", true},
    {"♭", "flat", "music", true},
    {"♮", "natural", "music", true},
    {"♯", "sharp", "music", true},
    {"†", "dagger", "cross", true},
    {"‡", "double dagger", "cross", true},
    {"‹", "single left-pointing angle quotation", "quote", true},
    {"›", "single right-pointing angle quotation", "quote", true},
    {"‽", "interrobang", "punctuation", true},
    {"⁂", "asterism", "break", true},
    {"⁃", "hyphen bullet", "list", true},
    {"⁎", "low asterisk", "star", true},
    {"⁑", "two asterisks aligned vertically", "footnote", true},
    {"⁒", "commercial minus sign", "math", true},
    {"⁓", "swung dash", "tilde", true},
    {"⁕", "flower punctuation", "ornament", true},
    {"☰", "trigram for heaven", "menu hamburger", true},
    {"⚠", "warning sign", "caution", true},
    {"⚡", "high voltage", "zap", true},
    {"⛔", "no entry", "stop", true},
    {"✅", "check mark button", "done", true},
    {"❌", "cross mark", "x", true},
    {"❓", "question mark", "help", true},
    {"❗", "exclamation mark", "bang", true},
    {"➕", "plus", "add", true},
    {"➖", "minus", "subtract", true},
    {"➗", "divide", "math", true},
};

SearchResult glyph_card(const Glyph& g, int score) {
  SearchResult r;
  r.title = std::string(g.ch) + "   " + g.name;
  r.subtitle = g.symbol ? "Symbol · enter copies" : "Emoji · enter copies";
  r.payload = g.ch;
  r.path = g.ch;
  r.action = ResultAction::Copy;
  r.score = score;
  r.kind_label = g.symbol ? "symbol" : "emoji";
  r.category = "mini";
  return r;
}

int score_glyph(std::string_view q, const Glyph& g) {
  if (q.empty()) return 9000;
  auto hay = to_lower_utf8(std::string(g.name) + " " + g.tags + " " + g.ch);
  auto needle = to_lower_utf8(std::string(q));
  if (hay == needle || std::string_view(g.name) == q) return 10000;
  if (hay.find(needle) != std::string::npos) return 9500;
  auto fz = score_fuzzy(needle, hay, g.name);
  if (!fz.matched) return 0;
  return 8000 + fz.score;
}

}  // namespace

std::vector<SearchResult> glyph_results(std::string_view query, bool symbols) {
  std::string q = std::string(query);
  while (!q.empty() && (q.front() == ' ' || q.front() == '\t'))
    q.erase(q.begin());
  while (!q.empty() && (q.back() == ' ' || q.back() == '\t'))
    q.pop_back();

  struct Hit {
    const Glyph* g;
    int score;
  };
  std::vector<Hit> hits;
  hits.reserve(64);
  for (const auto& g : kGlyphs) {
    if (g.symbol != symbols) continue;
    int sc = score_glyph(q, g);
    if (sc <= 0 && !q.empty()) continue;
    hits.push_back({&g, sc});
  }
  if (q.empty()) {
    if (hits.size() > 24) hits.resize(24);
  } else {
    std::sort(hits.begin(), hits.end(), [](const Hit& a, const Hit& b) {
      if (a.score != b.score) return a.score > b.score;
      return std::string_view(a.g->name) < std::string_view(b.g->name);
    });
    if (hits.size() > 32) hits.resize(32);
  }
  std::vector<SearchResult> out;
  out.reserve(hits.size());
  int n = 0;
  for (auto& h : hits) {
    out.push_back(glyph_card(*h.g, h.score - n));
    ++n;
  }
  if (out.empty()) {
    SearchResult r;
    r.title = symbols ? "No matching symbols" : "No matching emoji";
    r.subtitle = symbols ? "Try arrow, check, copyright, euro" : "Try smile, fire, heart, thumbs";
    r.action = ResultAction::None;
    r.score = 1000;
    r.kind_label = symbols ? "symbol" : "emoji";
    r.category = "mini";
    out.push_back(std::move(r));
  }
  return out;
}

}  // namespace wilfred
